services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: budgie
      POSTGRES_PASSWORD: budgie
      POSTGRES_DB: budgie
    ports:
      - "5432:5432"
    volumes:
      - budgie-db:/var/lib/postgresql/data

volumes:
  budgie-db:
